name: Fetch and Summarize Data (Master)
on: 
  push:
    branches:
      - master
  schedule:
    - cron: "*/15 * * * *"
    
jobs:
  summarize:
    name: summarize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        
      - name: Download and Generate JSON data
        run: node generate.js

      - name: Publish Latest Data
        run: node publish.js

      - name: Git Status
        run: git status
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Automated Action
          author_email: alastair@liquidx.net
          message: "(Automated) Data Update"
          add: "docs/*/*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
